# Generated by Django 5.1.2 on 2024-11-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('alt_username', models.JSONField(default=list)),
                ('total_media', models.IntegerField(default=0)),
                ('total_photo', models.IntegerField(default=0)),
                ('total_video', models.IntegerField(default=0)),
                ('profile_view', models.IntegerField(default=0)),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
