# Generated by Django 5.1.2 on 2024-11-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alt_username',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
